// Code generated by "stringer -type=MyEnum"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[First-0]
	_ = x[Second-1]
	_ = x[Third-2]
}

const _MyEnum_name = "FirstSecondThird"

var _MyEnum_index = [...]uint8{0, 5, 11, 16}

func (i MyEnum) String() string {
	if i < 0 || i >= MyEnum(len(_MyEnum_index)-1) {
		return "MyEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MyEnum_name[_MyEnum_index[i]:_MyEnum_index[i+1]]
}
