// Code generated by "stringer -type=MyPerson"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PersonA-3]
}

const _MyPerson_name = "PersonA"

var _MyPerson_index = [...]uint8{0, 7}

func (i MyPerson) String() string {
	i -= 3
	if i >= MyPerson(len(_MyPerson_index)-1) {
		return "MyPerson(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _MyPerson_name[_MyPerson_index[i]:_MyPerson_index[i+1]]
}
